/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supervcdstore.UI;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.ListModel;
import supervcdstore.Client;
import supervcdstore.ClientHandler;
import supervcdstore.bean.MusicAlbum;
import supervcdstore.bean.MusicAlbumPath;
import supervcdstore.bean.MusicKind;

/**
 *
 * @author Administrator
 */
public class MainFrame extends JFrame {

    private static Client client = new Client();
    private static List<MusicKind> infos;
    private static MainFrame mainFrame;
    private int selectMusicKindIndex;
    private static ClientHandler clientHandler;
//    private JMenuBar jMenuBar;
//    private JMenu jMenu_file;
//    private JMenu jMenu_options;
//    private JMenu jMenu_help;
//    /**
//     * 选项卡组件
//     */
//    private JTabbedPane tabbedPane;
//    /**
//     * 音乐页
//     */
//    private MusicPanel musicPanel;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("欢迎使用SuperVCDStore应用");
       
        middleShow();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel_music = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_music = new javax.swing.JList();
        jLabel_music_type = new javax.swing.JLabel();
        jComboBox_music_type = new javax.swing.JComboBox();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu_file = new javax.swing.JMenu();
        localJMenuItem = new javax.swing.JMenuItem();
        networkJMenuItem = new javax.swing.JMenuItem();
        webJMenuItem = new javax.swing.JMenuItem();
        jMenu_options = new javax.swing.JMenu();
        jMenu_help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("欢迎使用SuperVCDStore应用");

        jList_music.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_musicMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList_music);

        jLabel_music_type.setText("音乐类型");
        jLabel_music_type.setToolTipText("");

        jComboBox_music_type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox_music_typeMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel_musicLayout = new javax.swing.GroupLayout(jPanel_music);
        jPanel_music.setLayout(jPanel_musicLayout);
        jPanel_musicLayout.setHorizontalGroup(
            jPanel_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_musicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel_musicLayout.createSequentialGroup()
                        .addComponent(jLabel_music_type, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_music_type, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 610, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_musicLayout.setVerticalGroup(
            jPanel_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_musicLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_music_type, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_music_type, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("音乐", jPanel_music);

        jMenu_file.setText("文件");

        localJMenuItem.setText("本地");
        jMenu_file.add(localJMenuItem);

        networkJMenuItem.setText("网络");
        jMenu_file.add(networkJMenuItem);

        webJMenuItem.setText("互联网");
        jMenu_file.add(webJMenuItem);

        jMenuBar.add(jMenu_file);

        jMenu_options.setText("选项");
        jMenuBar.add(jMenu_options);

        jMenu_help.setText("帮助");
        jMenuBar.add(jMenu_help);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList_musicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_musicMouseClicked
        // TODO add your handling code here:
        MusicAlbum musicAlbum = infos.get(selectMusicKindIndex).getMusicAlbums().get(jList_music.getSelectedIndex());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MusicPanel musicPanel = new MusicPanel(musicAlbum,clientHandler);
                musicPanel.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                musicPanel.setVisible(true);
            }
        });

    }//GEN-LAST:event_jList_musicMouseClicked
    //该方法在鼠标点击确定之后调用
    private void jComboBox_music_typeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_music_typeMouseEntered
        // TODO add your handling code here:
        selectMusicKindIndex = jComboBox_music_type.getSelectedIndex();
        List<MusicAlbum> musicAlbums = infos.get(jComboBox_music_type.getSelectedIndex()).getMusicAlbums();
        String[] musicAlbumNames = new String[musicAlbums.size()];
        for (int i = 0; i < musicAlbums.size(); i++) {
            musicAlbumNames[i] = musicAlbums.get(i).getAlbumName();
        }
        ListModel jListModel = new DefaultComboBoxModel(musicAlbumNames);
        mainFrame.jList_music.setModel(jListModel);
        this.repaint();
    }//GEN-LAST:event_jComboBox_music_typeMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                infos = getInfo();
                mainFrame = new MainFrame();
                for (MusicKind iterator : infos) {
                    mainFrame.jComboBox_music_type.addItem(iterator.getKindName());
                }
                List<MusicAlbum> musicAlbums = infos.get(0).getMusicAlbums();
                String[] musicAlbumNames = new String[musicAlbums.size()];
                for (int i = 0; i < musicAlbums.size(); i++) {
                    musicAlbumNames[i] = musicAlbums.get(i).getAlbumName();
                }
                ListModel jListModel = new DefaultComboBoxModel(musicAlbumNames);
                mainFrame.jList_music.setModel(jListModel);
                mainFrame.setVisible(true);

            }
        });
    }

    /**
     * 使窗体居中显示
     */
    private void middleShow() {
        Dimension displaySize = Toolkit.getDefaultToolkit().getScreenSize(); // 获得显示器大小对象 
        Dimension frameSize = this.getSize();             // 获得窗口大小对象  
        if (frameSize.width > displaySize.width) {
            frameSize.width = displaySize.width;           // 窗口的宽度不能大于显示器的宽度  
        }
        this.setLocation((displaySize.width - frameSize.width) / 2,
                (displaySize.height - frameSize.height) / 2); // 设置窗口居中显示器显示  
        // 设置窗口为可见的，默认为不可见  
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox_music_type;
    private javax.swing.JLabel jLabel_music_type;
    private javax.swing.JList jList_music;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenu_file;
    private javax.swing.JMenu jMenu_help;
    private javax.swing.JMenu jMenu_options;
    private javax.swing.JPanel jPanel_music;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JMenuItem localJMenuItem;
    private javax.swing.JMenuItem networkJMenuItem;
    private javax.swing.JMenuItem webJMenuItem;
    // End of variables declaration//GEN-END:variables

    private static List<MusicKind> getInfo() {
        List<MusicKind> musicKinds1 = new ArrayList<>();
        if (client.login()) {
            clientHandler=client.getClientHandler();
            String musicInfoJson = clientHandler.getInfo();
            if (musicInfoJson != null) {
                Gson gson = new Gson();
                musicKinds1 = gson.fromJson(musicInfoJson, new TypeToken<List<MusicKind>>() {
                }.getType());
            }
        } else {
        }
        return musicKinds1;
    }
    
}
