/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supervcdstore.UI;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import supervcdstore.ClientHandler;
import supervcdstore.bean.Music;
import supervcdstore.bean.MusicAlbum;
import supervcdstore.utils.WindowsCenter;

/**
 *
 * @author yangy
 */
public class MusicPanel extends javax.swing.JFrame {

    /**
     * Creates new form MusicPanel
     */
    private List<Music> musics;
    private String musicAlbumId;
    private ClientHandler clientHandler;
    private String albumId;

    public MusicPanel(MusicAlbum musicAlbum, ClientHandler clientHandler) {
        initComponents();
        jLabel_Singer.setText(musicAlbum.getSinger());
        jLabel_albumName.setText(musicAlbum.getAlbumName());
        jLabel_kind.setText(musicAlbum.getKind());
        jLabel_price.setText(musicAlbum.getPrice());
        jLabel_time.setText(musicAlbum.getTime());
        musics = musicAlbum.getMusics();
        String[] musicNames = new String[musics.size()];
        for (int i = 0; i < musics.size(); i++) {
            musicNames[i] = musics.get(i).getMusicName();
        }
        musicAlbumId = musicAlbum.getId();
        String photoPath = clientHandler.getMusicAlbumPhoto(musicAlbumId);
        jLabel_AlbumPhoto.setIcon(new ImageIcon(photoPath));
        this.clientHandler = clientHandler;
        albumId = musicAlbum.getId();

        ListModel jListModel = new DefaultComboBoxModel(musicNames);
        jList_Music.setModel(jListModel);
        middleShow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Music = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_Singer = new javax.swing.JLabel();
        jLabel_albumName = new javax.swing.JLabel();
        jLabel_kind = new javax.swing.JLabel();
        jLabel_time = new javax.swing.JLabel();
        jLabel_price = new javax.swing.JLabel();
        jButton_BuyMusic = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel_AlbumPhoto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList_Music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_MusicMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList_Music);

        jLabel1.setText("歌手");

        jLabel2.setText("专辑名称");

        jLabel3.setText("类别");

        jLabel4.setText("长度");

        jLabel5.setText("价格");

        jLabel_Singer.setText("jLabel8");

        jLabel_albumName.setText("jLabel9");

        jLabel_kind.setText("jLabel10");

        jLabel_time.setText("jLabel11");

        jLabel_price.setText("jLabel12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_price)
                    .addComponent(jLabel_time)
                    .addComponent(jLabel_kind)
                    .addComponent(jLabel_albumName)
                    .addComponent(jLabel_Singer))
                .addContainerGap(234, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addContainerGap(290, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel_Singer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_albumName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_kind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_time)
                .addGap(18, 18, 18)
                .addComponent(jLabel_price)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel5)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        jLabel_Singer.getAccessibleContext().setAccessibleName("jLabel_Singer");
        jLabel_albumName.getAccessibleContext().setAccessibleName("jLabel_albumName");
        jLabel_kind.getAccessibleContext().setAccessibleName("jLabel_kind");
        jLabel_kind.getAccessibleContext().setAccessibleDescription("");
        jLabel_time.getAccessibleContext().setAccessibleName("jLabel_time");
        jLabel_price.getAccessibleContext().setAccessibleName("jLabel_price");

        jButton_BuyMusic.setText("购买");
        jButton_BuyMusic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_BuyMusicMouseClicked(evt);
            }
        });

        jButtonCancel.setText("取消");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(jLabel_AlbumPhoto);

        jLabel6.setText("歌名");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_BuyMusic)
                .addGap(32, 32, 32)
                .addComponent(jButtonCancel)
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_BuyMusic)
                    .addComponent(jButtonCancel)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList_MusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_MusicMouseClicked
        // TODO add your handling code here:
        String musicPath = clientHandler.getMusic(musics.get(jList_Music.getSelectedIndex()).getMusicId());
        System.out.println("soudao" + musicPath);
        MusicPlayerFrame player = null;
        player = new MusicPlayerFrame();
        player.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        WindowsCenter.Center(player);
        player.open();
        player.setVisible(true);
        //音乐的路径
        player.addMusic(musicPath);
        player.setSelectedAndPlay(musics.get(jList_Music.getSelectedIndex()).getMusicName());
    }//GEN-LAST:event_jList_MusicMouseClicked

    private void jButton_BuyMusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_BuyMusicMouseClicked
        // TODO add your handling code here:
        if (clientHandler.getMusicAlbum(albumId)) {
            JOptionPane.showMessageDialog(this, "购买音乐成功请到E:\\musicClent\\Album\\中查收");
        }


    }//GEN-LAST:event_jButton_BuyMusicMouseClicked

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //  new MusicPanel().setVisible(true);
            }
        });
    }

    private void middleShow() {
        Dimension displaySize = Toolkit.getDefaultToolkit().getScreenSize(); // 获得显示器大小对象 
        Dimension frameSize = this.getSize();             // 获得窗口大小对象  
        if (frameSize.width > displaySize.width) {
            frameSize.width = displaySize.width;           // 窗口的宽度不能大于显示器的宽度  
        }
        this.setLocation((displaySize.width - frameSize.width) / 2,
                (displaySize.height - frameSize.height) / 2); // 设置窗口居中显示器显示  
        // 设置窗口为可见的，默认为不可见  
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButton_BuyMusic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_AlbumPhoto;
    private javax.swing.JLabel jLabel_Singer;
    private javax.swing.JLabel jLabel_albumName;
    private javax.swing.JLabel jLabel_kind;
    private javax.swing.JLabel jLabel_price;
    private javax.swing.JLabel jLabel_time;
    private javax.swing.JList<String> jList_Music;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
